import { toAirtableAttachments } from "@/utils/airtableAttachments";

export const FIELD = {
  SPEECHES_DETAILED: "Speeches Detailed",
  TARGET_AUDIENCE: "Target Audience",
  DELIVERY_CONTEXT: "Delivery Context",
  FEE_LOCAL: "Fee Range Local",
  FEE_CONTINENTAL: "Fee Range Continental",
  FEE_INTERNATIONAL: "Fee Range International",
  FEE_VIRTUAL: "Fee Range Virtual",
  FEE_GENERAL: "Fee Range General",
  FIRST_NAME: "First Name",
  LAST_NAME: "Last Name",
  EMAIL: "Email",
  PROFILE_IMAGE: "Profile Image",
  HEADER_IMAGE: "Header Image",
} as const;

export function buildAirtableFieldsFromForm(form) {
  const profileImages = toAirtableAttachments(form["Profile Image"]);
  const headerImages = toAirtableAttachments(form["Header Image"]);
  const out: Record<string, any> = {
    [FIELD.FIRST_NAME]: form.firstName?.trim(),
    [FIELD.LAST_NAME]: form.lastName?.trim(),
    Title: form.title,
    "Professional Title": form.professionalTitle,
    Company: form.company,
    Location: form.location,
    Country: form.country,
    [FIELD.EMAIL]: form.email?.trim(),
    Phone: form.phone,
    Industry: form.industry,
    "Expertise Level": form.expertiseLevel,
    "Years Experience": form.yearsExperience,
    "Notable Achievements": form.notableAchievements,
    Achievements: form.achievements,
    Education: form.education,
    "Speaking Experience": form.speakingExperience,
    "Number of Events": form.numberOfEvents,
    "Largest Audience": form.largestAudience,
    "Virtual Experience": form.virtualExperience,
    "Expertise Areas": form.expertiseAreas,
    "Speaking Topics": form.speakingTopics,
    "Key Messages": form.keyMessage ? [form.keyMessage] : undefined,
    "Professional Bio": form.professionalBio,
    [FIELD.SPEECHES_DETAILED]: form.speechesDetailed,
    "Speakers Delivery Style": form.speakersDeliveryStyle,
    "Why the audience should listen to these topics": form.whyAudience,
    "What the speeches will address": form.whatAddress,
    "What participants will learn": form.whatLearn,
    "What the audience will take home": form.whatTakeHome,
    "Benefits for the individual": form.benefitsIndividual,
    "Benefits for the organisation": form.benefitsOrganisation,
    "Video Link 1": form.videoLink1,
    "Video Link 2": form.videoLink2,
    "Video Link 3": form.videoLink3,
    "Spoken Languages": form.spokenLanguages,
    [FIELD.TARGET_AUDIENCE]: Array.isArray(form.targetAudience) ? form.targetAudience : [],
    [FIELD.DELIVERY_CONTEXT]: Array.isArray(form.deliveryContext) ? form.deliveryContext : [],
    [FIELD.FEE_LOCAL]: form.feeRangeLocal || undefined,
    [FIELD.FEE_CONTINENTAL]: form.feeRangeContinental || undefined,
    [FIELD.FEE_INTERNATIONAL]: form.feeRangeInternational || undefined,
    [FIELD.FEE_VIRTUAL]: form.feeRangeVirtual || undefined,
    [FIELD.FEE_GENERAL]: form.feeRangeGeneral || undefined,
    "Display Fee": form.displayFee,
    "Travel Willingness": form.travelWillingness,
    "Travel Requirements": form.travelRequirements,
    Website: form.website,
    LinkedIn: form.linkedin,
    Twitter: form.twitter,
    References: form.references,
    "PA Name": form.paName,
    "PA Email": form.paEmail,
    "PA Phone": form.paPhone,
    "Banking Details": form.bankingDetails,
    "Special Requirements": form.specialRequirements,
    "Additional Info": form.additionalInfo,
  };
  if (typeof profileImages !== 'undefined') out[FIELD.PROFILE_IMAGE] = profileImages;
  if (typeof headerImages !== 'undefined') out[FIELD.HEADER_IMAGE] = headerImages;
  return out;
}
